In [17]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import numpy as np

In [18]:
df_x = pd.read_csv("pre_processed_data/df_x_n_mfcc52_pca10.csv") 

In [19]:
df_y = pd.read_csv("pre_processed_data/df_y_n_mfcc52_pca10.csv")

In [20]:
x = np.array(df_x).reshape(-1, 10, 1)

In [21]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df_y)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
unique_elements, counts_elements = np.unique(y_encoded, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[  0   1   2   3   4]
 [174 229 210 222 138]]


In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2, random_state = 42)

In [24]:
# Create the model
model = Sequential()

# Add convolutional layers
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(13, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layers
model.add(Flatten())

# Add dense layers
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(5, activation='softmax')) 


# Compile the model
optimiser = tf.keras.optimizers.Adam(learning_rate = 0.0002)
cb = [EarlyStopping(patience=10,monitor='accuracy',mode='max',restore_best_weights=True)]
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=16, validation_data=(x_test, y_test), callbacks = cb)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/100


49/49 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.2107 - loss: 5.6685 - val_accuracy: 0.2821 - val_loss: 2.1793
Epoch 2/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2325 - loss: 2.9551 - val_accuracy: 0.4103 - val_loss: 1.4164
Epoch 3/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2882 - loss: 2.2028 - val_accuracy: 0.4410 - val_loss: 1.2834
Epoch 4/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3314 - loss: 1.8234 - val_accuracy: 0.5077 - val_loss: 1.2109
Epoch 5/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.3663 - loss: 1.5657 - val_accuracy: 0.5077 - val_loss: 1.2231
Epoch 6/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3326 - loss: 1.5972 - val_accuracy: 0.4923 - val_loss: 1.1653
Epoch 7/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3920 - loss: 1.4269 - val_accuracy: 0.5128 - val_loss: 1.1440
Epoch 8/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4306 - loss: 1.3659 - val_accuracy: 0.5333 - val_loss: 1

In [25]:
y_pred = model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step


In [26]:
y_pred

array([[2.89603369e-03, 9.85144496e-01, 2.84983800e-03, 1.18986063e-03,
        7.91976973e-03],
       [4.42010816e-03, 6.55733421e-03, 1.12845115e-01, 8.62301409e-01,
        1.38759604e-02],
       [1.34278997e-03, 3.32975690e-03, 1.33302584e-01, 8.55127096e-01,
        6.89777825e-03],
       [1.70374528e-01, 5.16997203e-02, 2.51276433e-01, 1.46244928e-01,
        3.80404443e-01],
       [5.64472168e-04, 6.82820380e-02, 1.14211300e-02, 9.18940663e-01,
        7.91614759e-04],
       [8.42367182e-04, 4.76597017e-03, 1.06516607e-01, 8.79929602e-01,
        7.94546492e-03],
       [3.14298831e-02, 4.64543551e-02, 3.49742591e-01, 9.44453850e-02,
        4.77927864e-01],
       [1.53561459e-18, 1.00000000e+00, 6.37895377e-16, 9.91726588e-15,
        1.58971451e-15],
       [2.21692157e-04, 9.95829761e-01, 8.50518816e-04, 1.67051586e-03,
        1.42756058e-03],
       [1.57879933e-03, 9.94809031e-01, 7.73356121e-04, 1.06014172e-03,
        1.77858083e-03],
       [1.09828547e-01, 7.5763

In [27]:
y_pred_classes

array([1, 3, 3, 4, 3, 3, 4, 1, 1, 1, 2, 2, 3, 3, 1, 0, 1, 2, 2, 2, 1, 0,
       2, 2, 2, 2, 4, 2, 2, 0, 1, 2, 0, 4, 2, 0, 2, 3, 0, 2, 1, 2, 3, 4,
       0, 4, 3, 0, 0, 1, 0, 0, 4, 2, 2, 1, 1, 1, 3, 0, 3, 4, 3, 2, 3, 3,
       2, 1, 1, 1, 0, 2, 4, 2, 1, 3, 3, 1, 0, 3, 2, 1, 1, 2, 1, 4, 0, 3,
       1, 3, 2, 1, 2, 2, 1, 1, 3, 0, 1, 0, 2, 4, 1, 3, 4, 2, 3, 2, 1, 2,
       1, 0, 0, 4, 1, 2, 2, 2, 2, 2, 1, 2, 2, 3, 3, 2, 1, 2, 2, 2, 2, 1,
       3, 1, 3, 0, 2, 1, 2, 3, 2, 1, 1, 3, 1, 4, 4, 1, 0, 2, 1, 2, 0, 0,
       2, 2, 1, 1, 3, 1, 3, 4, 3, 3, 4, 1, 4, 3, 4, 1, 2, 3, 1, 3, 3, 2,
       3, 1, 1, 4, 1, 3, 2, 1, 2, 3, 4, 2, 2, 2, 1, 3, 2, 2, 2],
      dtype=int64)

In [28]:
accuracy = accuracy_score(y_test, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.6974358974358974


In [29]:
class_report = classification_report(y_test, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.61      0.71        33
           1       0.98      0.89      0.93        56
           2       0.42      0.68      0.52        37
           3       0.75      0.67      0.71        45
           4       0.52      0.46      0.49        24

    accuracy                           0.70       195
   macro avg       0.71      0.66      0.67       195
weighted avg       0.75      0.70      0.71       195



In [30]:
y_pred = model.predict(x_train)
y_pred_classes = y_pred.argmax(axis=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [31]:
accuracy = accuracy_score(y_train, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.8174807197943444


In [32]:
class_report = classification_report(y_train, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.81      0.88       141
           1       1.00      0.97      0.99       173
           2       0.58      0.83      0.68       173
           3       0.87      0.80      0.83       177
           4       0.84      0.61      0.70       114

    accuracy                           0.82       778
   macro avg       0.85      0.80      0.82       778
weighted avg       0.85      0.82      0.82       778

