In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import numpy as np

C:\Users\Yash Thakar\AppData\Local\Temp\ipykernel_8076\3230018081.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df_x = pd.read_csv("pre_processed_data/df_x_n_mfcc52_ae10.csv") 

In [3]:
df_y = pd.read_csv("pre_processed_data/df_y_n_mfcc52_ae10.csv")

In [4]:
x = np.array(df_x).reshape(-1, 10, 1)

In [5]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df_y)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
unique_elements, counts_elements = np.unique(y_encoded, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[  0   1   2   3   4]
 [174 212 210 222 138]]


In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2, random_state = 42)

In [8]:
# Create the model
model = Sequential()

# Add convolutional layers
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(13, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layers
model.add(Flatten())

# Add dense layers
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(5, activation='softmax')) 


# Compile the model
optimiser = tf.keras.optimizers.Adam(learning_rate = 0.0002)
cb = [EarlyStopping(patience=10,monitor='accuracy',mode='max',restore_best_weights=True)]
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=16, validation_data=(x_test, y_test), callbacks = cb)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.2112 - loss: 6.5412 - val_accuracy: 0.1615 - val_loss: 1.7840
Epoch 2/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.1746 - loss: 3.3097 - val_accuracy: 0.3125 - val_loss: 1.5297
Epoch 3/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2085 - loss: 2.2680 - val_accuracy: 0.2500 - val_loss: 1.5701
Epoch 4/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2478 - loss: 1.7911 - val_accuracy: 0.2656 - val_loss: 1.5502
Epoch 5/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2165 - loss: 1.7379 - val_accuracy: 0.2812 - val_loss: 1.5457
Epoch 6/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2270 - loss: 1.6702 - val_accuracy: 0.3125 - val_loss: 1.5452
Epoch 7/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2183 - loss: 1.6458 - val_accuracy: 0.3438 - val_loss: 1.5124
Epoch 8/100
48/48 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.2614 - loss: 1.5731 - val_accuracy: 0.2

In [9]:
y_pred = model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step  


In [10]:
y_pred

array([[4.22859401e-01, 4.87801999e-01, 4.63815667e-02, 1.92970727e-02,
        2.36600060e-02],
       [2.54328936e-01, 3.50277275e-01, 1.57334536e-01, 1.25444070e-01,
        1.12615198e-01],
       [2.83775002e-01, 3.66290361e-01, 1.37325540e-01, 1.08559720e-01,
        1.04049422e-01],
       [1.03417553e-01, 1.49081543e-01, 2.56821036e-01, 3.01928729e-01,
        1.88751101e-01],
       [1.92291304e-01, 1.89072236e-01, 2.11385205e-01, 2.24470422e-01,
        1.82780817e-01],
       [1.15764320e-01, 1.61937043e-01, 2.47621775e-01, 2.84741044e-01,
        1.89935863e-01],
       [3.96954000e-01, 4.78875726e-01, 6.09072745e-02, 2.94132698e-02,
        3.38497497e-02],
       [3.39923054e-01, 4.10991222e-01, 1.06481731e-01, 6.94040954e-02,
        7.31999129e-02],
       [1.01609878e-01, 1.47152841e-01, 2.58176088e-01, 3.04554075e-01,
        1.88507140e-01],
       [1.26661777e-01, 2.01992676e-01, 2.36749753e-01, 2.67123282e-01,
        1.67472497e-01],
       [9.68859121e-02, 1.4205

In [11]:
y_pred_classes

array([1, 1, 1, 3, 3, 3, 1, 1, 3, 3, 3, 1, 3, 3, 1, 3, 1, 3, 3, 1, 3, 3,
       1, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 3, 1, 3, 1, 3,
       3, 3, 1, 1, 3, 3, 1, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3,
       1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 3, 1, 3, 1, 1, 3, 3, 3, 1, 3,
       3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 1, 1, 3, 3, 1, 3, 3, 2, 3, 3, 3,
       3, 0, 3, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 3, 3, 1, 1, 1, 3, 1, 3, 1,
       1, 3, 1, 1, 3, 3, 3, 1, 0, 3, 1, 1, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3,
       3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 1, 3, 3, 1,
       3, 0, 1, 3, 3, 3, 1, 3, 3, 3, 1, 3, 1, 3, 1, 1], dtype=int64)

In [12]:
accuracy = accuracy_score(y_test, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.3854166666666667


In [13]:
class_report = classification_report(y_test, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.09      0.16        34
           1       0.47      0.70      0.56        40
           2       0.00      0.00      0.00        48
           3       0.34      0.98      0.50        44
           4       0.00      0.00      0.00        26

    accuracy                           0.39       192
   macro avg       0.36      0.35      0.24       192
weighted avg       0.35      0.39      0.26       192



c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()

In [14]:
y_pred = model.predict(x_train)
y_pred_classes = y_pred.argmax(axis=1)

20/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


In [15]:
accuracy = accuracy_score(y_train, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.38219895287958117


In [16]:
class_report = classification_report(y_train, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.17      0.29       140
           1       0.45      0.56      0.50       172
           2       1.00      0.01      0.02       162
           3       0.32      0.95      0.48       178
           4       0.00      0.00      0.00       112

    accuracy                           0.38       764
   macro avg       0.56      0.34      0.26       764
weighted avg       0.57      0.38      0.28       764



c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()