In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import numpy as np

C:\Users\Yash Thakar\AppData\Local\Temp\ipykernel_14608\3230018081.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df_x = pd.read_csv("pre_processed_data/df_x_n_mfcc52.csv")

In [3]:
df_y = pd.read_csv("pre_processed_data/df_y_n_mfcc52.csv")

In [4]:
df_x.reset_index(drop=True, inplace=True)

In [5]:
x = np.array(df_x).reshape(-1, 52, 1)

In [6]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df_y)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [7]:
unique_elements, counts_elements = np.unique(y_encoded, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[  0   1   2   3   4]
 [174 229 210 222 138]]


In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2, random_state = 42)

In [9]:
# Create the model
model = Sequential()

# Add convolutional layers
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(52, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(128, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layers
model.add(Flatten())

# Add dense layers
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(5, activation='softmax')) 


# Compile the model
optimiser = tf.keras.optimizers.Adam(learning_rate = 0.0002)
cb = [EarlyStopping(patience=10,monitor='accuracy',mode='max',restore_best_weights=True)]
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=16, validation_data=(x_test, y_test), callbacks = cb)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.1963 - loss: 2.6900 - val_accuracy: 0.3487 - val_loss: 1.5817
Epoch 2/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.2258 - loss: 1.6871 - val_accuracy: 0.5128 - val_loss: 1.5246
Epoch 3/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.2831 - loss: 1.6110 - val_accuracy: 0.5487 - val_loss: 1.4408
Epoch 4/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3260 - loss: 1.5337 - val_accuracy: 0.5077 - val_loss: 1.4054
Epoch 5/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3592 - loss: 1.4775 - val_accuracy: 0.5538 - val_loss: 1.3296
Epoch 6/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3530 - loss: 1.4524 - val_accuracy: 0.5385 - val_loss: 1.2759
Epoch 7/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4017 - loss: 1.3874 - val_accuracy: 0.5436 - val_loss: 1.2355
Epoch 8/100
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4122 - loss: 1.3250 - val_accuracy: 0.5436 - 

In [10]:
y_pred = model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


In [11]:
y_pred

array([[1.10515010e-08, 1.00000000e+00, 5.86394648e-13, 9.76411507e-10,
        1.14181449e-10],
       [5.12881816e-05, 6.52759196e-03, 6.27061017e-05, 9.93339598e-01,
        1.87770765e-05],
       [5.80329811e-07, 2.27704621e-03, 4.01618678e-07, 9.97721851e-01,
        1.06727839e-07],
       [3.46529931e-01, 2.81268042e-02, 1.41854107e-01, 4.23930325e-02,
        4.41096157e-01],
       [7.46080843e-07, 2.51109974e-04, 8.08935226e-07, 9.99747217e-01,
        1.28749079e-07],
       [3.31664421e-02, 5.19309230e-02, 7.64456928e-01, 8.88500586e-02,
        6.15956932e-02],
       [7.08942255e-03, 5.47916687e-04, 8.92859221e-01, 1.94081862e-03,
        9.75626484e-02],
       [3.27815746e-17, 1.00000000e+00, 3.43920478e-24, 1.96237351e-18,
        5.47395616e-21],
       [1.10812928e-10, 1.00000000e+00, 1.29619123e-15, 1.11715491e-10,
        1.29570356e-12],
       [1.17010488e-04, 9.99839306e-01, 9.77962145e-07, 2.63140173e-05,
        1.63644763e-05],
       [5.26439771e-02, 5.1928

In [12]:
y_pred_classes

array([1, 3, 3, 4, 3, 2, 2, 1, 1, 1, 4, 3, 1, 3, 1, 0, 1, 0, 4, 2, 1, 0,
       2, 0, 2, 2, 4, 2, 4, 0, 1, 4, 2, 4, 2, 4, 2, 3, 0, 2, 1, 2, 3, 4,
       0, 4, 3, 0, 0, 1, 0, 0, 2, 2, 2, 1, 1, 1, 3, 0, 2, 2, 3, 2, 3, 3,
       2, 1, 1, 1, 4, 2, 4, 3, 1, 3, 3, 1, 0, 3, 2, 1, 1, 2, 1, 4, 0, 3,
       1, 2, 2, 1, 2, 2, 1, 1, 3, 0, 1, 0, 0, 3, 1, 3, 2, 0, 1, 4, 1, 2,
       1, 4, 0, 4, 1, 4, 2, 4, 2, 4, 1, 0, 2, 4, 3, 2, 1, 2, 2, 3, 3, 1,
       1, 1, 3, 0, 2, 1, 2, 3, 2, 1, 1, 3, 1, 2, 4, 1, 4, 3, 1, 0, 4, 4,
       2, 3, 1, 1, 2, 1, 3, 2, 3, 3, 4, 1, 4, 3, 4, 1, 2, 3, 2, 3, 3, 2,
       3, 1, 1, 4, 1, 3, 0, 1, 3, 3, 4, 2, 2, 0, 1, 3, 4, 3, 2],
      dtype=int64)

In [13]:
accuracy = accuracy_score(y_test, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.8512820512820513


In [14]:
class_report = classification_report(y_test, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.64      0.74        33
           1       1.00      0.95      0.97        56
           2       0.77      0.97      0.86        37
           3       0.90      0.82      0.86        45
           4       0.63      0.79      0.70        24

    accuracy                           0.85       195
   macro avg       0.84      0.83      0.83       195
weighted avg       0.87      0.85      0.85       195



In [15]:
y_pred = model.predict(x_train)
y_pred_classes = y_pred.argmax(axis=1)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [16]:
accuracy = accuracy_score(y_train, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.8894601542416453


In [17]:
class_report = classification_report(y_train, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.79      0.85       141
           1       1.00      0.99      1.00       173
           2       0.80      0.92      0.86       173
           3       0.90      0.88      0.89       177
           4       0.84      0.81      0.82       114

    accuracy                           0.89       778
   macro avg       0.89      0.88      0.88       778
weighted avg       0.89      0.89      0.89       778

