In [8]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import numpy as np

In [9]:
df_x = pd.read_csv("urbansound8k_mfcc/13_reduced (1).csv") 

In [10]:
df_x

Feature_1   Feature_2   Feature_3  Feature_4  Feature_5  Feature_6  \
0    -211.93698   62.581220 -122.813156 -60.745296 -13.893755 -29.789837   
1    -417.00525   99.336624  -42.995586  51.073326   9.853778   7.969693   
2    -452.39316  112.362530  -37.578075  43.195866   8.631845  15.379369   
3    -406.47922   91.196610  -25.043556  42.784523  11.586844   5.054164   
4    -439.63873  103.862240  -42.658787  50.690285  12.209422  15.873466   
...         ...         ...         ...        ...        ...        ...   
8727 -391.00000  125.000000  -40.600000  25.900000   1.730000   5.580000   
8728 -339.42715   76.409100  -35.309883  41.984040 -22.963875 -13.623511   
8729 -297.00000  102.000000  -36.800000  26.800000  -0.249000   3.960000   
8730 -337.00000  115.000000  -44.800000  25.000000  -9.890000  -2.150000   
8731 -307.41763   83.306740  -25.756512  35.448110   4.414006  -0.893325   

      Feature_7  Feature_8  Feature_9  Feature_10  Feature_11  Feature_12  \
0     -3.978871  11.682741  12.963834    8.336420   -6.529818   -2.996104   
1     11.197088   1.929118   7.030397    4.270228   -3.584725   13.890946   
2     16.882149   1.233047   6.833121    3.900115   -5.168850    8.300045   
3     12.431632  -1.599949   6.656064    1.442354   -4.624870   14.211007   
4     11.729268   1.533586  11.292243    2.548621   -7.290973   10.374461   
...         ...        ...        ...         ...         ...         ...   
8727  16.900000   7.890000   3.490000   -4.570000    2.730000    0.209000   
8728  27.856026  -9.215821  -5.666290   13.024159   -9.010244   -1.397294   
8729  11.100000   1.910000   0.677000   -1.800000   -1.640000   -4.760000   
8730  22.700000   0.234000  -0.123000   10.200000   -2.780000   -7.000000   
8731   9.015661   8.213615  -1.967305   -1.941081    1.252807    2.707129   

      Feature_13  
0     -12.887945  
1      -2.764493  
2       1.904138  
3       0.434271  
4       2.101837  
...          ...  
8727   -4.850000  
8728   -0.384217  
8729   -9.210000  
8730   -0.481000  
8731   -7.433314  

[8732 rows x 13 columns]

In [11]:
df_y = pd.read_csv("urbansound8k_mfcc/mfcc52_y.csv")

In [12]:
x = np.array(df_x).reshape(-1, 13, 1)

In [13]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df_y)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
unique_elements, counts_elements = np.unique(y_encoded, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[   0    1    2    3    4    5    6    7    8    9]
 [1000  429 1000 1000 1000 1000  374 1000  929 1000]]


In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2, random_state = 42)

In [20]:
# Create the model
model = Sequential()

# Add convolutional layers
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(13, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layers
model.add(Flatten())

# Add dense layers
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(10, activation='softmax')) 


# Compile the model
optimiser = tf.keras.optimizers.Adam(learning_rate = 0.0002)
cb = [EarlyStopping(patience=10,monitor='accuracy',mode='max',restore_best_weights=True)]
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=16, validation_data=(x_test, y_test), callbacks = cb)

Epoch 1/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.1274 - loss: 4.7920 - val_accuracy: 0.2564 - val_loss: 2.0482
Epoch 2/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.2197 - loss: 2.1431 - val_accuracy: 0.3669 - val_loss: 1.9266
Epoch 3/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.2656 - loss: 2.0233 - val_accuracy: 0.4110 - val_loss: 1.8349
Epoch 4/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.3078 - loss: 1.9466 - val_accuracy: 0.4402 - val_loss: 1.6962
Epoch 5/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.3534 - loss: 1.8751 - val_accuracy: 0.4310 - val_loss: 1.6777
Epoch 6/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.3697 - loss: 1.8045 - val_accuracy: 0.4665 - val_loss: 1.5938
Epoch 7/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.3898 - loss: 1.7577 - val_accuracy: 0.4596 - val_loss: 1.5623
Epoch 8/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.4036 - loss: 1.7127 - val_accu

In [21]:
y_pred = model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [22]:
y_pred

array([[7.53685758e-02, 2.05620036e-01, 1.40449004e-02, ...,
        8.72160196e-02, 3.64010513e-01, 4.73930985e-02],
       [3.23050481e-04, 4.08787699e-03, 1.10648535e-02, ...,
        1.17669064e-04, 8.44187569e-04, 6.64489865e-01],
       [4.41824390e-08, 4.35985578e-03, 2.86255636e-05, ...,
        1.00772058e-06, 8.23178489e-05, 2.85614951e-04],
       ...,
       [3.32564935e-02, 4.99169668e-03, 5.79742268e-02, ...,
        3.73778306e-03, 4.61186777e-04, 1.41807556e-01],
       [1.10436250e-02, 4.39084461e-03, 3.23341340e-02, ...,
        3.68286943e-04, 1.48098113e-03, 3.21804315e-01],
       [1.25901076e-08, 8.50500888e-04, 1.47116316e-05, ...,
        5.73727038e-11, 9.76267755e-01, 4.63794335e-04]], dtype=float32)

In [23]:
y_pred_classes

array([8, 9, 4, ..., 5, 3, 8], dtype=int64)

In [24]:
accuracy = accuracy_score(y_test, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.7298225529479107


In [25]:
class_report = classification_report(y_test, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.78      0.75       203
           1       0.92      0.56      0.70        86
           2       0.50      0.66      0.57       183
           3       0.74      0.71      0.72       201
           4       0.77      0.67      0.72       206
           5       0.84      0.89      0.86       193
           6       0.79      0.51      0.62        72
           7       0.84      0.87      0.85       208
           8       0.78      0.85      0.81       165
           9       0.64      0.60      0.62       230

    accuracy                           0.73      1747
   macro avg       0.75      0.71      0.72      1747
weighted avg       0.74      0.73      0.73      1747



In [26]:
y_pred = model.predict(x_train)
y_pred_classes = y_pred.argmax(axis=1)

219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [27]:
accuracy = accuracy_score(y_train, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.7670722977809592


In [28]:
class_report = classification_report(y_train, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.81      0.82       797
           1       0.85      0.56      0.67       343
           2       0.58      0.71      0.64       817
           3       0.75      0.69      0.72       799
           4       0.89      0.75      0.81       794
           5       0.81      0.90      0.85       807
           6       0.84      0.49      0.62       302
           7       0.88      0.91      0.89       792
           8       0.84      0.88      0.86       764
           9       0.60      0.68      0.64       770

    accuracy                           0.77      6985
   macro avg       0.79      0.74      0.75      6985
weighted avg       0.78      0.77      0.77      6985

