In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import numpy as np

C:\Users\Yash Thakar\AppData\Local\Temp\ipykernel_22628\3230018081.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [5]:
df_x = pd.read_csv("urbansound8k_mfcc/autoencoder_data_x.csv") 

In [6]:
df_y = pd.read_csv("urbansound8k_mfcc/mfcc52_y.csv")

In [7]:
x = np.array(df_x).reshape(-1, 23, 1)

In [8]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df_y)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
unique_elements, counts_elements = np.unique(y_encoded, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[   0    1    2    3    4    5    6    7    8    9]
 [1000  429 1000 1000 1000 1000  374 1000  929 1000]]


In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2, random_state = 42)

In [15]:
# Create the model
model = Sequential()

# Add convolutional layers
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(23, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layers
model.add(Flatten())

# Add dense layers
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(23, activation='softmax')) 


# Compile the model
optimiser = tf.keras.optimizers.Adam(learning_rate = 0.0002)
cb = [EarlyStopping(patience=10,monitor='accuracy',mode='max',restore_best_weights=True)]
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=16, validation_data=(x_test, y_test), callbacks = cb)

Epoch 1/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.1052 - loss: 4.4453 - val_accuracy: 0.3045 - val_loss: 2.3399
Epoch 2/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2272 - loss: 2.4481 - val_accuracy: 0.4196 - val_loss: 1.9196
Epoch 3/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.3075 - loss: 2.1344 - val_accuracy: 0.4408 - val_loss: 1.7328
Epoch 4/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3327 - loss: 1.9818 - val_accuracy: 0.4820 - val_loss: 1.6294
Epoch 5/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.3789 - loss: 1.8350 - val_accuracy: 0.5192 - val_loss: 1.5100
Epoch 6/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4085 - loss: 1.7604 - val_accuracy: 0.5346 - val_loss: 1.4674
Epoch 7/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.4336 - loss: 1.7098 - val_accuracy: 0.5501 - val_loss: 1.3973
Epoch 8/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4542 - loss: 1.6154 - val_accu

In [16]:
y_pred = model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step


In [17]:
y_pred

array([[8.51048098e-05, 3.09957936e-02, 3.87990405e-03, ...,
        2.13889670e-13, 1.74445724e-14, 5.20836527e-14],
       [1.69637144e-06, 8.32608086e-04, 1.22722136e-04, ...,
        1.60856052e-28, 1.29923776e-28, 1.09014513e-25],
       [8.97561314e-09, 5.76369275e-05, 4.38839180e-07, ...,
        3.43845506e-34, 3.13143136e-33, 3.91798099e-34],
       ...,
       [5.50849109e-07, 6.62293189e-08, 5.68718804e-07, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.19292841e-05, 7.03001686e-04, 1.19944639e-03, ...,
        1.67891637e-20, 8.29730090e-21, 1.18447344e-20],
       [4.68139287e-14, 1.00660463e-06, 2.07360517e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]], dtype=float32)

In [18]:
y_pred_classes

array([8, 9, 4, ..., 5, 4, 8], dtype=int64)

In [19]:
accuracy = accuracy_score(y_test, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.7836290784201488


In [20]:
class_report = classification_report(y_test, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.90      0.87       203
           1       0.81      0.72      0.76        86
           2       0.69      0.64      0.67       183
           3       0.83      0.76      0.79       201
           4       0.79      0.69      0.74       206
           5       0.86      0.92      0.89       193
           6       0.78      0.71      0.74        72
           7       0.85      0.84      0.84       208
           8       0.85      0.95      0.89       165
           9       0.58      0.66      0.62       230

    accuracy                           0.78      1747
   macro avg       0.79      0.78      0.78      1747
weighted avg       0.79      0.78      0.78      1747



In [21]:
y_pred = model.predict(x_train)
y_pred_classes = y_pred.argmax(axis=1)

219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [22]:
accuracy = accuracy_score(y_train, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.8637079455977094


In [23]:
class_report = classification_report(y_train, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.97      0.94       797
           1       0.95      0.85      0.90       343
           2       0.80      0.76      0.78       817
           3       0.84      0.79      0.82       799
           4       0.89      0.83      0.86       794
           5       0.94      0.95      0.94       807
           6       0.91      0.68      0.78       302
           7       0.93      0.96      0.95       792
           8       0.94      0.95      0.94       764
           9       0.64      0.78      0.71       770

    accuracy                           0.86      6985
   macro avg       0.88      0.85      0.86      6985
weighted avg       0.87      0.86      0.86      6985

