In [19]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score, classification_report
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from sklearn.model_selection import train_test_split
import numpy as np

In [20]:
df_x = pd.read_csv("urbansound8k_mfcc/mfcc52_x.csv")

In [21]:
df_y = pd.read_csv("urbansound8k_mfcc/mfcc52_y.csv")

In [22]:
df_x

Feature_1  Feature_2  Feature_3  Feature_4  Feature_5  Feature_6  \
0        -212.0       62.6     -123.0      -60.7    -13.900    -29.800   
1        -417.0       99.3      -43.0       51.1      9.850      7.970   
2        -452.0      112.0      -37.6       43.2      8.630     15.400   
3        -406.0       91.2      -25.0       42.8     11.600      5.050   
4        -440.0      104.0      -42.7       50.7     12.200     15.900   
...         ...        ...        ...        ...        ...        ...   
8727     -391.0      125.0      -40.6       25.9      1.730      5.580   
8728     -339.0       76.4      -35.3       42.0    -23.000    -13.600   
8729     -297.0      102.0      -36.8       26.8     -0.249      3.960   
8730     -337.0      115.0      -44.8       25.0     -9.890     -2.150   
8731     -307.0       83.3      -25.8       35.4      4.410     -0.893   

      Feature_7  Feature_8  Feature_9  Feature_10  ...  Feature_43  \
0         -3.98     11.700     13.000        8.34  ...       -4.76   
1         11.20      1.930      7.030        4.27  ...       -2.62   
2         16.90      1.230      6.830        3.90  ...       -2.54   
3         12.40     -1.600      6.660        1.44  ...       -1.65   
4         11.70      1.530     11.300        2.55  ...        0.76   
...         ...        ...        ...         ...  ...         ...   
8727      16.90      7.890      3.490       -4.57  ...       -3.50   
8728      27.90     -9.220     -5.670       13.00  ...       -5.84   
8729      11.10      1.910      0.677       -1.80  ...       -2.46   
8730      22.70      0.234     -0.123       10.20  ...       -3.26   
8731       9.02      8.210     -1.970       -1.94  ...      -11.00   

      Feature_44  Feature_45  Feature_46  Feature_47  Feature_48  Feature_49  \
0        -4.4000      -5.720       0.375       -5.80      1.2300      -5.300   
1         1.2000      -1.970       1.420       -1.29      1.1600      -1.960   
2        -0.2630      -1.220       0.395       -3.04      0.6010      -2.660   
3        -0.0941      -0.778       1.150       -2.66      0.7280      -2.420   
4         0.6140      -1.230       1.230       -1.53      0.5590      -0.303   
...          ...         ...         ...         ...         ...         ...   
8727      0.2410      -1.960       1.530       -1.52     -0.0476      -2.500   
8728     -5.3000       1.090       0.322       -7.31      4.2200       1.050   
8729     -0.4380      -4.350      -1.020       -1.70      2.2000       1.950   
8730     -2.8400      -4.810      -0.192       -3.81      0.3530      -1.260   
8731     -3.3100       0.232      -3.280       -7.63      4.9000      -4.300   

      Feature_50  Feature_51  Feature_52  
0          2.220      -1.370      -2.490  
1          0.416      -1.380       2.070  
2          0.746      -1.870       1.860  
3          0.897       0.503       0.693  
4          1.000      -0.729       1.910  
...          ...         ...         ...  
8727       3.760      -2.420       0.925  
8728      -5.420      -1.120       7.280  
8729      -0.341      -7.150      -3.020  
8730      -1.700      -2.590       1.920  
8731      -7.420       1.590      11.200  

[8732 rows x 52 columns]

In [23]:
df_y

1
0             dog_bark
1     children_playing
2     children_playing
3     children_playing
4     children_playing
...                ...
8727          car_horn
8728          car_horn
8729          car_horn
8730          car_horn
8731          car_horn

[8732 rows x 1 columns]

In [24]:
x = np.array(df_x).reshape(-1, 52, 1)

In [25]:
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(df_y)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
unique_elements, counts_elements = np.unique(y_encoded, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[   0    1    2    3    4    5    6    7    8    9]
 [1000  429 1000 1000 1000 1000  374 1000  929 1000]]


In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, 
                                                    test_size=0.2, random_state = 42)

In [28]:
# Create the model
model = Sequential()

# Add convolutional layers
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(52, 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Conv1D(64, kernel_size=3, activation='relu'))
model.add(MaxPooling1D(pool_size=2))

# Flatten the output of the convolutional layers
model.add(Flatten())

# Add dense layers
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(10, activation='softmax')) 


# Compile the model
optimiser = tf.keras.optimizers.Adam(learning_rate = 0.0002)
cb = [EarlyStopping(patience=10,monitor='accuracy',mode='max',restore_best_weights=True)]
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=100, batch_size=16, validation_data=(x_test, y_test), callbacks = cb)

c:\Users\Yash Thakar\PROGRAMMING\Quantum\env\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Epoch 1/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.1551 - loss: 2.7619 - val_accuracy: 0.3921 - val_loss: 1.9160
Epoch 2/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3239 - loss: 1.9160 - val_accuracy: 0.5243 - val_loss: 1.5185
Epoch 3/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4295 - loss: 1.6577 - val_accuracy: 0.6096 - val_loss: 1.2781
Epoch 4/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5038 - loss: 1.4711 - val_accuracy: 0.6812 - val_loss: 1.0912
Epoch 5/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5449 - loss: 1.3350 - val_accuracy: 0.7012 - val_loss: 1.0085
Epoch 6/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5780 - loss: 1.2501 - val_accuracy: 0.7281 - val_loss: 0.9258
Epoch 7/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6084 - loss: 1.1507 - val_accuracy: 0.7619 - val_loss: 0.8186
Epoch 8/100
437/437 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6438 - loss: 1.0685 - val_accu

In [29]:
y_pred = model.predict(x_test)
y_pred_classes = y_pred.argmax(axis=1)

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step


In [30]:
y_pred

array([[3.17980914e-04, 4.54291221e-05, 1.97404279e-05, ...,
        6.63589453e-05, 9.78123248e-01, 1.10564448e-04],
       [3.70957736e-08, 3.93185692e-05, 1.84586515e-05, ...,
        3.37910365e-06, 6.54780905e-08, 9.99844909e-01],
       [8.39249474e-24, 1.43501899e-14, 1.05186305e-17, ...,
        3.67826906e-12, 4.88931984e-19, 1.46630873e-14],
       ...,
       [8.02131797e-17, 1.35121345e-10, 3.62711570e-13, ...,
        1.08752477e-15, 3.63796979e-11, 1.77607859e-07],
       [7.20335467e-12, 6.69398141e-05, 4.03530187e-08, ...,
        1.64667835e-09, 7.15596332e-11, 9.99930143e-01],
       [2.95079565e-27, 6.68224024e-28, 1.99836201e-26, ...,
        1.13067989e-28, 1.00000000e+00, 2.68387197e-27]], dtype=float32)

In [31]:
y_pred_classes

array([8, 9, 4, ..., 5, 9, 8], dtype=int64)

In [32]:
accuracy = accuracy_score(y_test, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.9072696050372067


In [33]:
class_report = classification_report(y_test, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.96      0.94       203
           1       0.98      0.94      0.96        86
           2       0.80      0.86      0.83       183
           3       0.86      0.88      0.87       201
           4       0.93      0.87      0.90       206
           5       0.90      0.97      0.94       193
           6       0.91      0.85      0.88        72
           7       0.96      0.95      0.95       208
           8       0.96      0.94      0.95       165
           9       0.89      0.85      0.87       230

    accuracy                           0.91      1747
   macro avg       0.91      0.91      0.91      1747
weighted avg       0.91      0.91      0.91      1747



In [34]:
y_pred = model.predict(x_train)
y_pred_classes = y_pred.argmax(axis=1)

 25/219 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 

219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [35]:
accuracy = accuracy_score(y_train, y_pred_classes)
print(f'Accuracy Score: {accuracy}')

Accuracy Score: 0.9891195418754474


In [36]:
class_report = classification_report(y_train, y_pred_classes)
print('Classification Report:\n', class_report)

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       797
           1       1.00      1.00      1.00       343
           2       0.96      1.00      0.98       817
           3       0.98      0.97      0.98       799
           4       0.99      0.99      0.99       794
           5       1.00      1.00      1.00       807
           6       0.99      0.96      0.98       302
           7       0.99      0.99      0.99       792
           8       0.99      0.99      0.99       764
           9       1.00      0.98      0.99       770

    accuracy                           0.99      6985
   macro avg       0.99      0.99      0.99      6985
weighted avg       0.99      0.99      0.99      6985

